apiVersion: v1
kind: Service
metadata:
  name: onos-service
spec:
  selector:
    app: onos
  type: NodePort
  ports:
    - name: onos       
      port: 8181
      targetPort: 8181    
      nodePort: 30000     
    - name: openflow
      port: 6653
      targetPort: 6653
      nodePort: 31000 
    - name: ssh
      port: 8101
      targetPort: 8101
      nodePort: 32000
